### ISSUE TITLE
Mais detalhes sobre funções apply()?

### ISSUE THREAD

**Issue by danilofreire** [carloscinelli/livroR#1]
Olá Carlos!

Muito legal o post novo! Eu sempre tive muitos problemas em entender essas funções, ajudou bastante. Eu só tenho uma pequena sugestão: que tal um breve glossário com as muitas formas de apply()? Embora o texto de vocês seja muito bom, talvez uma breve nota explicando quando usar sapply ou lapply, por exemplo. De resto, ótimo trabalho como sempre :)

Abração!

**Comment by carloscinelli** [comment]
Valeu, Danilo! As partes do livro estão saindo fora de ordem, na verdade antes dessa seção há uma seção inteira sobre apply (apply, lapply, sapply, mapply, rowSums, colSums, rowMeans, colMeans etc). O foco nessa seção é de introduzir a estratégia split, apply, combine, pressupondo que a pessoa já tenha lido sobre apply antes (a seção do apply será logo após a parte de estruturas de programação, como if-else, for, while etc). Abs

**Comment by danilofreire** [comment]
Puxa, desculpe pelo comentário fora de propósito então :) Se isso já foi feito, esqueça o que eu disse! haha

No aguardo das outras partes :)

**Comment by carloscinelli** [comment]
Que isso, não precisa se desculpar, eu não tinha sido claro no propósito do post, tentei dar uma esclarecida no texto do blog! Acho super importante o feedback e eu que agradeço pelo comentário!
